config/routes.rb
Rails.application.routes.draw do
  get 'search_engine/index', to: 'search_engine#index', as: 'search_engine_index'
  get 'search_engine/ethnoidiogloss', to: 'search_engine#ethnoidiogloss', as: 'search_engine_ethnoidiogloss'
  get 'search_engine/concordance', to: 'search_engine#concordance', as: 'search_engine_concordance'
  get 'search_engine/frequency_vocabulary', to: 'search_engine#frequency_vocabulary', as: 'search_engine_frequency_vocabulary'
  get 'search_engine/grammar_dictionaries', to: 'search_engine#grammar_dictionaries', as: 'search_engine_dictionaries'
  
  
  # get 'welcome/testpage'
  get 'welcome/index'
  root 'welcome#index'
  
  resources :comments
  resources :ethnoidioglosses
  resources :grammar_dictionaries
  resources :frequency_vocabularies
  resources :concordances
  resources :books
  resources :authors
  resources :notebooks
  resources :users
  resources :roles
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :ethnoidioglosses
    has_many :notebooks
    
    validates :first_name, presence: true
    validates :second_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true

    include PgSearch::Model

    def name_with_initial
        "#{second_name} #{first_name.first}. #{last_name.first}."
    end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :book_eigs
  has_many :ethnoidioglosses, through: :book_eigs
  has_many :concordance_books
  has_many :concordances, through: :concordance_books
  has_one :frequency_vocabulary 

  validates :name, presence: true
  validates :text, presence: true

  attr_accessor :book_file
  include PgSearch::Model

end

app/models/book_eig.rb
class BookEig < ApplicationRecord
  belongs_to :book
  belongs_to :ethnoidiogloss
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ethnoidiogloss
end

app/models/concordance.rb
class Concordance < ApplicationRecord
    has_many :concordance_books
    has_many :books, through: :concordance_books
end

app/models/concordance_book.rb
class ConcordanceBook < ApplicationRecord
  belongs_to :concordance
  belongs_to :book
end

app/models/eig_status_vote.rb
class EigStatusVote < ApplicationRecord
  belongs_to :user
  belongs_to :ethnoidiogloss
end

app/models/ethnoidiogloss.rb
class Ethnoidiogloss < ApplicationRecord
  belongs_to :author
  belongs_to :user
  has_many :book_eigs
  has_many :books, through: :book_eigs
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :role
  has_many :notebooks

  def name_with_initial
    "#{second_name} #{first_name.first}. #{last_name.first}."
end
end

app/controllers/concordances_controller.rb
class ConcordancesController < ApplicationController
  before_action :set_concordance, only: [:show, :edit, :update, :destroy]

  # GET /concordances
  # GET /concordances.json
  def index
    @concordances = Concordance.all
  end

  # GET /concordances/1
  # GET /concordances/1.json
  def show
  end

  # GET /concordances/new
  def new
    @concordance = Concordance.new
  end

  # GET /concordances/1/edit
  def edit
  end

  # POST /concordances
  # POST /concordances.json
  def create
    @concordance = Concordance.new(concordance_params)

    respond_to do |format|
      if @concordance.save
        format.html { redirect_to @concordance, notice: 'Concordance was successfully created.' }
        format.json { render :show, status: :created, location: @concordance }
      else
        format.html { render :new }
        format.json { render json: @concordance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concordances/1
  # PATCH/PUT /concordances/1.json
  def update
    respond_to do |format|
      if @concordance.update(concordance_params)
        format.html { redirect_to @concordance, notice: 'Concordance was successfully updated.' }
        format.json { render :show, status: :ok, location: @concordance }
      else
        format.html { render :edit }
        format.json { render json: @concordance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concordances/1
  # DELETE /concordances/1.json
  def destroy
    @concordance.destroy
    respond_to do |format|
      format.html { redirect_to concordances_url, notice: 'Concordance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concordance
      @concordance = Concordance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concordance_params
      params.require(:concordance).permit(:concordance, :is_it_lemma, :width)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concordances_helper.rb
module ConcordancesHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testpage_helper.rb
module TestpageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/concordances/_form.html.haml
= form_for @concordance do |f|
  - if @concordance.errors.any?
    #error_explanation
      %h2= "#{pluralize(@concordance.errors.count, "error")} prohibited this concordance from being saved:"
      %ul
        - @concordance.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :Слово
    = f.text_area :concordance, class: "form-control", type: "string", placeholder: "Слово"
  .field
    = f.label :Конкорданс
    = f.text_area :concordance, class: "form-control", type: "text", placeholder: "Конкорданс"
  .field
    = f.label :Лемма?
    = f.check_box :is_it_lemma, type: "checkbox"
  .field
    = f.label :Ширина
    = f.number_field :width, class: "form-control", type: "integer", placeholder: "Введите ширину (число)"
  .actions
    = f.submit 'Сохранить', class: "btn btn-light"

app/views/concordances/edit.html.haml
%h1.text-center Редактировать конкорданс

= render 'form'

= link_to 'Просмотр', @concordance, class: "btn btn-light"
\|
= link_to 'Назад', concordances_path, class: "btn btn-light"

app/views/concordances/index.html.haml
%h1.text-center Список конкордансов

%table.table.table-striped.table-hover
  %thead
    %tr
      %th{:scope => "col"} Слово
      %th{:scope => "col"} Конкорданс
      %th{:scope => "col"} Лемма?
      %th{:scope => "col"} Ширина
      %th{:scope => "col"}
      %th{:scope => "col"}
      %th{:scope => "col"}

  %tbody
    - @concordances.each do |concordance|
      %tr
        %td= concordance.word
        %td= concordance.concordance
        %td= concordance.is_it_lemma
        %td= concordance.width
        %td= link_to 'Просмотреть', concordance, class: "btn btn-light"
        %td= link_to 'Редактировать', edit_concordance_path(concordance), class: "btn btn-light"
        %td= link_to 'Удалить', concordance, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-light"

%br

= link_to 'Добавить конкорданс', new_concordance_path, class: "btn btn-light"

app/views/concordances/new.html.haml
%h1.text-center Новый конкорданс

= render 'form'

= link_to 'Назад', concordances_path, class: "btn btn-light"

app/views/concordances/show.html.haml
%p#notice= notice

%p.text-center 
  %b Слово:
  = @concordance.word
%p
  %b Конкорданс:
  = @concordance.concordance
%p
  %b Лемма?:
  = @concordance.is_it_lemma
%p
  %b Ширина:
  = @concordance.width

= link_to 'Изменить', edit_concordance_path(@concordance), class: "btn btn-light"
\|
= link_to 'Назад', concordances_path, class: "btn btn-light"