config/routes.rb
Rails.application.routes.draw do
  get 'search_engine/index', to: 'search_engine#index', as: 'search_engine_index'
  get 'search_engine/ethnoidiogloss', to: 'search_engine#ethnoidiogloss', as: 'search_engine_ethnoidiogloss'
  get 'search_engine/concordance', to: 'search_engine#concordance', as: 'search_engine_concordance'
  get 'search_engine/frequency_vocabulary', to: 'search_engine#frequency_vocabulary', as: 'search_engine_frequency_vocabulary'
  get 'search_engine/grammar_dictionaries', to: 'search_engine#grammar_dictionaries', as: 'search_engine_dictionaries'
  
  
  # get 'welcome/testpage'
  get 'welcome/index'
  root 'welcome#index'
  
  resources :comments
  resources :ethnoidioglosses
  resources :grammar_dictionaries
  resources :frequency_vocabularies
  resources :concordances
  resources :books
  resources :authors
  resources :notebooks
  resources :users
  resources :roles
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :ethnoidioglosses
    has_many :notebooks
    
    validates :first_name, presence: true
    validates :second_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true

    include PgSearch::Model

    def name_with_initial
        "#{second_name} #{first_name.first}. #{last_name.first}."
    end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :book_eigs
  has_many :ethnoidioglosses, through: :book_eigs
  has_many :concordance_books
  has_many :concordances, through: :concordance_books
  has_one :frequency_vocabulary 

  validates :name, presence: true
  validates :text, presence: true

  attr_accessor :book_file
  include PgSearch::Model

end

app/models/book_eig.rb
class BookEig < ApplicationRecord
  belongs_to :book
  belongs_to :ethnoidiogloss
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ethnoidiogloss
end

app/models/concordance.rb
class Concordance < ApplicationRecord
    has_many :concordance_books
    has_many :books, through: :concordance_books
end

app/models/concordance_book.rb
class ConcordanceBook < ApplicationRecord
  belongs_to :concordance
  belongs_to :book
end

app/models/eig_status_vote.rb
class EigStatusVote < ApplicationRecord
  belongs_to :user
  belongs_to :ethnoidiogloss
end

app/models/ethnoidiogloss.rb
class Ethnoidiogloss < ApplicationRecord
  belongs_to :author
  belongs_to :user
  has_many :book_eigs
  has_many :books, through: :book_eigs
end

app/models/grammar_dictionary.rb
class GrammarDictionary < ApplicationRecord
  belongs_to :book
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :role
  has_many :notebooks

  def name_with_initial
    "#{second_name} #{first_name.first}. #{last_name.first}."
end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)
    @notenote.user_id = session[:user_id]
    respond_to do |format|
      if @notebook.save
        format.html { redirect_to @notebook, notice: 'Notebook was successfully created.' }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to @notebook, notice: 'Notebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.html { redirect_to notebooks_url, notice: 'Notebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notebook_params
      params.require(:notebook).permit(:name, :description, :user_id)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testpage_helper.rb
module TestpageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/notebooks/_form.html.haml
= form_for @notebook do |f|
  - if @notebook.errors.any?
    #error_explanation
      %h2= "#{pluralize(@notebook.errors.count, "error")} prohibited this notebook from being saved:"
      %ul
        - @notebook.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :Название
    = f.text_field :name, class: "form-control", type: "string", placeholder: "Название"
  .field
    = f.label :Содержание
    = f.text_area :description, class: "form-control", type: "text", placeholder: "Содержание"
  .actions
    = f.submit 'Сохранить', class: "btn btn-light"

app/views/notebooks/edit.html.haml
%h1.text-center Редактировать Блокнот

= render 'form'

= link_to 'Просмотр', @notebook, class: "btn btn-light"
\|
= link_to 'Назад', notebooks_path, class: "btn btn-light"

app/views/notebooks/index.html.haml
%h1.text-center Блокноты

%table.table.table-striped
  %thead
    %tr
      %th{:scope => "col"} Название
      %th{:scope => "col"} Описание
      -# %th{:scope => "col"} User
      %th{:scope => "col"}
      %th{:scope => "col"}
      %th{:scope => "col"}
  %tbody
    - @notebooks.each do |notebook|
      %tr
        %td= notebook.name
        %td= notebook.description
        -# %td= notebook.user
        %td= link_to 'Просмотр', notebook, class: "btn btn-light"
        %td= link_to 'Редактировать', edit_notebook_path(notebook), class: "btn btn-light"
        %td= link_to 'Удалить', notebook, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-light"

%br

= link_to 'Создать блокнот', new_notebook_path, class: "btn btn-light"

app/views/notebooks/new.html.haml
%h1.text-center Новый блокнот

= render 'form'

= link_to 'Назад', notebooks_path, class: "btn btn-light"

app/views/notebooks/show.html.haml
%p#notice= notice

%p.text-center 
  %b Название:
  = @notebook.name
%p
  %b Содержание:
  = @notebook.description
-# %p
-#   %b User:
-#   = @notebook.user

= link_to 'Редактировать', edit_notebook_path(@notebook), class: "btn btn-light"
\|
= link_to 'Назад', notebooks_path, class: "btn btn-light"