config/routes.rb
Rails.application.routes.draw do
  get 'search_engine/index', to: 'search_engine#index', as: 'search_engine_index'
  get 'search_engine/ethnoidiogloss', to: 'search_engine#ethnoidiogloss', as: 'search_engine_ethnoidiogloss'
  get 'search_engine/concordance', to: 'search_engine#concordance', as: 'search_engine_concordance'
  get 'search_engine/frequency_vocabulary', to: 'search_engine#frequency_vocabulary', as: 'search_engine_frequency_vocabulary'
  get 'search_engine/grammar_dictionaries', to: 'search_engine#grammar_dictionaries', as: 'search_engine_dictionaries'
  
  
  # get 'welcome/testpage'
  get 'welcome/index'
  root 'welcome#index'
  
  resources :comments
  resources :ethnoidioglosses
  resources :grammar_dictionaries
  resources :frequency_vocabularies
  resources :concordances
  resources :books
  resources :authors
  resources :notebooks
  resources :users
  resources :roles
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :ethnoidioglosses
    has_many :notebooks
    
    validates :first_name, presence: true
    validates :second_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true

    include PgSearch::Model

    def name_with_initial
        "#{second_name} #{first_name.first}. #{last_name.first}."
    end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :book_eigs
  has_many :ethnoidioglosses, through: :book_eigs
  has_many :concordance_books
  has_many :concordances, through: :concordance_books
  has_one :frequency_vocabulary 

  validates :name, presence: true
  validates :text, presence: true

  attr_accessor :book_file
  include PgSearch::Model

end

app/models/book_eig.rb
class BookEig < ApplicationRecord
  belongs_to :book
  belongs_to :ethnoidiogloss
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ethnoidiogloss
end

app/models/concordance.rb
class Concordance < ApplicationRecord
    has_many :concordance_books
    has_many :books, through: :concordance_books
end

app/models/concordance_book.rb
class ConcordanceBook < ApplicationRecord
  belongs_to :concordance
  belongs_to :book
end

app/models/eig_status_vote.rb
class EigStatusVote < ApplicationRecord
  belongs_to :user
  belongs_to :ethnoidiogloss
end

app/models/ethnoidiogloss.rb
class Ethnoidiogloss < ApplicationRecord
  belongs_to :author
  belongs_to :user
  has_many :book_eigs
  has_many :books, through: :book_eigs
end

app/models/grammar_dictionary.rb
class GrammarDictionary < ApplicationRecord
  belongs_to :book
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :role
  has_many :notebooks

  def name_with_initial
    "#{second_name} #{first_name.first}. #{last_name.first}."
end
end

app/controllers/grammar_dictionaries_controller.rb
class GrammarDictionariesController < ApplicationController
  before_action :set_grammar_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /grammar_dictionaries
  # GET /grammar_dictionaries.json
  def index
    @grammar_dictionaries = GrammarDictionary.all
  end

  # GET /grammar_dictionaries/1
  # GET /grammar_dictionaries/1.json
  def show
  end

  # GET /grammar_dictionaries/new
  def new
    @grammar_dictionary = GrammarDictionary.new
  end

  # GET /grammar_dictionaries/1/edit
  def edit
  end

  # POST /grammar_dictionaries
  # POST /grammar_dictionaries.json
  def create
    @grammar_dictionary = GrammarDictionary.new(grammar_dictionary_params)

    respond_to do |format|
      if @grammar_dictionary.save
        format.html { redirect_to @grammar_dictionary, notice: 'Grammar dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @grammar_dictionary }
      else
        format.html { render :new }
        format.json { render json: @grammar_dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grammar_dictionaries/1
  # PATCH/PUT /grammar_dictionaries/1.json
  def update
    respond_to do |format|
      if @grammar_dictionary.update(grammar_dictionary_params)
        format.html { redirect_to @grammar_dictionary, notice: 'Grammar dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @grammar_dictionary }
      else
        format.html { render :edit }
        format.json { render json: @grammar_dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grammar_dictionaries/1
  # DELETE /grammar_dictionaries/1.json
  def destroy
    @grammar_dictionary.destroy
    respond_to do |format|
      format.html { redirect_to grammar_dictionaries_url, notice: 'Grammar dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grammar_dictionary
      @grammar_dictionary = GrammarDictionary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grammar_dictionary_params
      params.require(:grammar_dictionary).permit(:dictionary, :book_id)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grammar_dictionaries_helper.rb
module GrammarDictionariesHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testpage_helper.rb
module TestpageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/grammar_dictionaries/_form.html.haml
= form_for @grammar_dictionary do |f|
  - if @grammar_dictionary.errors.any?
    #error_explanation
      %h2= "#{pluralize(@grammar_dictionary.errors.count, "error")} prohibited this grammar_dictionary from being saved:"
      %ul
        - @grammar_dictionary.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :"Грамматический словарь"
    = f.text_area :dictionary, class: "form-control", type: "text", placeholder: "Грамматический словарь"
  .control-group
    = f.label :Книги, class: 'control-label'
    .controls
      = collection_select( :ethnoidiogloss, :book_id, Book.all, :id, :name, {  }, { :multiple => false, class: "form-control"})
  .actions
    = f.submit 'Сохранить', class: "btn btn-light"

app/views/grammar_dictionaries/edit.html.haml
%h1.text-center Редактировать грамматический словарь

= render 'form'

= link_to 'Просмотр', @grammar_dictionary, class: "btn btn-light"
\|
= link_to 'Назад', grammar_dictionaries_path, class: "btn btn-light"

app/views/grammar_dictionaries/index.html.haml
%h1.text-center Список Грамматических словарей

%table.table.table-hover
  %thead
    %tr
      %th{:scope => "col"} Словарь
      %th{:scope => "col"} Книги
      %th{:scope => "col"}
      %th{:scope => "col"}
      %th{:scope => "col"}

  %tbody
    - @grammar_dictionaries.each do |grammar_dictionary|
      %tr
        %td= grammar_dictionary.dictionary
        %td= grammar_dictionary.book
        %td= link_to 'Просмотр', grammar_dictionary, class: "btn btn-light"
        %td= link_to 'Редактировать', edit_grammar_dictionary_path(grammar_dictionary), class: "btn btn-light"
        %td= link_to 'Удалить', grammar_dictionary, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-light"

%br

= link_to 'Добавить грамматический словарь', new_grammar_dictionary_path, class: "btn btn-light"

app/views/grammar_dictionaries/new.html.haml
%h1.text-center Новый грамматический словарь

= render 'form'

= link_to 'Назад', grammar_dictionaries_path, class: "btn btn-light"

app/views/grammar_dictionaries/show.html.haml
%p#notice= notice

%p.text-center
  %b Грамматический словарь:
  = @grammar_dictionary.dictionary
%p
  %b Книги:
  = @grammar_dictionary.book

= link_to 'Изменить', edit_grammar_dictionary_path(@grammar_dictionary), class: "btn btn-light"
\|
= link_to 'Назад', grammar_dictionaries_path, class: "btn btn-light"